# https://pub.dev/packages/pedantic_mono
include: package:pedantic_mono/analysis_options.yaml
analyzer:
  exclude:
    - lib/l10n/messages_*.dart
    - lib/**/*.g.dart
    - lib/**/*.freezed.dart
    - test/**/*.mocks.dart
    - test/**/*.reflectable.dart
    - lib/generated_plugin_registrant.dart
    - ios/**
  errors:
    invalid_annotation_target: ignore
    use_build_context_synchronously: ignore
